services:
  lotto:
    build: .
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app
    networks:
      - webproxy

networks:
  webproxy:
    external: true
